// <auto-generated />
using kw2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace kw2.Migrations
{
    [DbContext(typeof(CarsRentalContext))]
    [Migration("20171121061541_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kw2.Models.AdditionalService", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.HasKey("ServiceId");

                    b.ToTable("AdditionalServices");
                });

            modelBuilder.Entity("kw2.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CarNumber");

                    b.Property<DateTime>("DateOfIssue");

                    b.Property<int>("DayRentalCar");

                    b.Property<int>("EngineNumber");

                    b.Property<int>("Mileage");

                    b.Property<int?>("ModelId");

                    b.Property<int>("RegistrationNumber");

                    b.HasKey("CarId");

                    b.HasIndex("ModelId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("kw2.Models.CarRental", b =>
                {
                    b.Property<int>("RentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CarId");

                    b.Property<int?>("CustomerId");

                    b.Property<DateTime>("DateOfIssue");

                    b.Property<int?>("EmployeeId");

                    b.Property<int>("PaymentNote");

                    b.Property<int>("PriceRental");

                    b.Property<int>("RentalPeriod");

                    b.Property<DateTime>("ReturnDate");

                    b.Property<int?>("ServiceId");

                    b.HasKey("RentId");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("CarsRental");
                });

            modelBuilder.Entity("kw2.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adress");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Name");

                    b.Property<int>("PassportData");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("kw2.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartWork");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("kw2.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Specification");

                    b.HasKey("ModelId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("kw2.Models.Car", b =>
                {
                    b.HasOne("kw2.Models.Model", "Model")
                        .WithMany("Cars")
                        .HasForeignKey("ModelId");
                });

            modelBuilder.Entity("kw2.Models.CarRental", b =>
                {
                    b.HasOne("kw2.Models.Car", "Car")
                        .WithMany("CarsRental")
                        .HasForeignKey("CarId");

                    b.HasOne("kw2.Models.Customer", "Customer")
                        .WithMany("CarsRental")
                        .HasForeignKey("CustomerId");

                    b.HasOne("kw2.Models.Employee", "Employee")
                        .WithMany("CarsRental")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("kw2.Models.AdditionalService", "AdditionalService")
                        .WithMany("CarsRental")
                        .HasForeignKey("ServiceId");
                });
#pragma warning restore 612, 618
        }
    }
}
